Workflow:
  Name: Simple task flow
  Rules:
      - Name: Early to Middle
        From: S20
        To: 
          - State: S25
            Calculation: |
              BalanceAmount > 30000 and CustomerAge <= 30
            Tags:
              - HighIncome
              - LessThan30
          - State: S30
            Tags:
              - HighIncome
              - Over30
      - From: S30

              